# Generated by Django 5.2.8 on 2025-11-22 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Prep_time', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('difficulty', models.IntegerField(choices=[(1, 'EASY'), (2, 'MEDIUM'), (3, 'HARD')])),
                ('vegetarian', models.BooleanField()),
                ('recipe_img', models.ImageField(upload_to='recipe/')),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
